package unit.test.kotlin.menggunakan_assertions.case1.exception

class ValidationException(message: String) : Throwable(message)